dead = ["Ghandi", "David", "Einstein"]
print(dead[0] + ', you are cordially invited to dinner from the afterlife to the "not dead life"')
print(dead[1] + ', you are cordially invited to dinner from the afterlife to the "not dead life"')
print(dead[-1] + ', you are cordially invited to dinner from the afterlife to the "not dead life"\n')#added an extra line, to separate the different sections
pdead= dead.pop(0)
print(pdead + ", I'm sorry you weren't able to make it \n")# added an extra line to separate the different sections
dead.append("Kadie")
print(dead[0] + ', you are cordially invited to dinner from the afterlife to the "not dead life"')
print(dead[1] + ', you are cordially invited to dinner from the afterlife to the "not dead life"')
print(dead[-1] + ', you are cordially invited to dinner from the afterlife to the "not dead life"\n')
print("Everyone, good news we found a bigger dinner table!\n")
dead.insert(0, "Alexander the Great")
dead.insert(2, "Marie Curie")
dead.append("John Paul")
print(dead)
print(dead[0] + ', you are cordially invited to dinner from the afterlife to the "not dead life"')
print(dead[1] + ', you are cordially invited to dinner from the afterlife to the "not dead life"')
print(dead[2] + ', you are cordially invited to dinner from the afterlife to the "not dead life"')
print(dead[3] + ', you are cordially invited to dinner from the afterlife to the "not dead life"')
print(dead[4] + ', you are cordially invited to dinner from the afterlife to the "not dead life"')
print(dead[-1] + ', you are cordially invited to dinner from the afterlife to the "not dead life"\n')