functions=[".append", ".insert", "del_",".pop",".remove",".sort","sorted(",".reverse","sort(reverse=True)","len("]
print(functions)
functions.append("print")
print(functions)
functions.insert(4, "recover pop")
print(functions)
del functions[-1]
print(functions)
pfun=functions.pop()
print(functions)
print(pfun)
functions.remove("del_")
print(functions)
functions.sort()
print(functions)
functions.reverse()
print(functions)
print(sorted(functions))
functions.reverse()# did an extra reverse to prove that the reverse sort is working note (this reverse flips the order, while sort reverse always does the opposite of alphabetical)
print(functions)
functions.sort(reverse=True)
print(functions)
print(len(functions))
